#!/usr/bin/env ruby

require_relative 'lib/init'

opts = Trollop::options do
  opt :verbose, "Verbose mode"
  opt :debug, "Verbose mode"
  opt :dry, "Dry mode (don't send email)"
  opt :email, "Email addresses to send to", :type => :string, :required => true
  opt :subreddit, "Subreddit to trawl", :type => :string, :required => true
  opt :limit, "Limit the number of images to display", :type => :integer, :default => 5
end

Trollop::die :email, "must be provided if not running dry mode" if !opts[:dry] && !opts[:email]

$VERBOSE_ON = opts[:verbose] ? true : false
$DEBUG_ON = opts[:debug] ? true : false
$DRY_ON = opts[:dry] ? true : false

$logger = Logging.logger(STDOUT)
$logger.level = :off
$logger.level = :info if $VERBOSE_ON
$logger.level = :debug if $DEBUG_ON

debug_log(opts)

Resque.enqueue(RedditEmailerWorker, opts)