#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
Bundler.require(:default, :development)

require_relative '../lib/utils'
require_relative '../lib/reddit/emailer'

include Utils

opts = Trollop::options do
  opt :verbose, "Verbose mode"
  opt :debug, "Verbose mode"
  opt :dry, "Dry mode (don't send email)"
  opt :email, "Email addresses to send to", :type => :string
  opt :subreddit, "Subreddit to trawl", :type => :string, :required => true
  opt :limit, "Limit the number of images to display", :type => :integer, :default => 5
end

Trollop::die :email, "must be provided if not running dry mode" if !opts[:dry] && !opts[:email]

$VERBOSE_ON = opts[:verbose] ? true : false
$DEBUG_ON = opts[:debug] ? true : false
$DRY_ON = opts[:dry] ? true : false

$logger = Logging.logger(STDOUT)
$logger.level = :off
$logger.level = :info if $VERBOSE_ON
$logger.level = :debug if $DEBUG_ON

debug_log(opts)

$BASE_CONFIG = YAML.load_file('config/config.yml')
$CONFIG = $BASE_CONFIG['app']

begin
  Reddit::Emailer.new(opts[:subreddit], opts[:limit], opts[:email] ? opts[:email].split(',') : [])
rescue  => e
  if $BASE_CONFIG['errbit']['enable']
    require 'toadhopper'
    Toadhopper.new($BASE_CONFIG['errbit']['api_key'], :notify_host => $BASE_CONFIG['errbit']['host']).post!(e)
  else
    raise
  end
end